"""initial schema

Revision ID: 1864a1eb302a
Revises: 
Create Date: 2026-10-06 01:18:25.797530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1864a1eb302a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_extraction_evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_version', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.String(length=100), nullable=False),
    sa.Column('evaluator_version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'partial', 'failed', name='aiextractionevaluationrunstatus', native_enum=False, length=32), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('failed_case_count', sa.Integer(), nullable=False),
    sa.Column('aggregate_metrics', sa.JSON(), nullable=True),
    sa.Column('case_results', sa.JSON(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('thresholds_passed', sa.Boolean(), nullable=True),
    sa.Column('error_summary', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_extraction_evaluation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_extraction_evaluation_runs_dataset_version'), ['dataset_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_extraction_evaluation_runs_status'), ['status'], unique=False)

    op.create_table('ingestion_job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=80), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', 'partial', name='ingestionjobstatus', native_enum=False, length=16), nullable=False),
    sa.Column('trigger_type', sa.Enum('cli', 'scheduled', 'admin', name='ingestionjobtrigger', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_job_runs_job_name'), ['job_name'], unique=False)
        batch_op.create_index('ix_ingestion_job_runs_name_started', ['job_name', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_job_runs_source_key'), ['source_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_job_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_ingestion_job_runs_status_started', ['status', 'started_at'], unique=False)
        batch_op.create_index('uq_ingestion_job_runs_running_name', ['job_name'], unique=True, sqlite_where=sa.text("status = 'running'"), postgresql_where=sa.text("status = 'running'"))

    op.create_table('parliamentary_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('abbreviation', sa.String(length=100), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('legislature', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parliamentary_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parliamentary_groups_institution'), ['institution'], unique=False)
        batch_op.create_index(batch_op.f('ix_parliamentary_groups_legislature'), ['legislature'], unique=False)

    op.create_table('political_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('abbreviation', sa.String(length=100), nullable=True),
    sa.Column('official_website_url', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('active_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('politicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_given_name', sa.String(length=200), nullable=False),
    sa.Column('canonical_family_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('politicians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_politicians_birth_date'), ['birth_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_politicians_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index('ix_politicians_normalized_name_birth_date', ['normalized_name', 'birth_date'], unique=False)

    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_title', sa.String(length=1000), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('exact_statement', sa.Text(), nullable=True),
    sa.Column('proposal_type', sa.Enum('proposal', 'legislative_proposal', 'government_initiative', 'explicit_promise', name='proposaltype', native_enum=False, length=64), nullable=False),
    sa.Column('introduced_at', sa.Date(), nullable=True),
    sa.Column('current_status', sa.Enum('announced', 'introduced', 'assigned', 'under_review', 'approved', 'rejected', 'withdrawn', 'enacted', 'completed', 'superseded', 'lapsed', 'returned', name='proposalstatus', native_enum=False, length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposals_current_status'), ['current_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposals_introduced_at'), ['introduced_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposals_proposal_type'), ['proposal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposals_published_at'), ['published_at'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_key'), ['key'], unique=True)

    op.create_table('parliamentary_group_source_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parliamentary_group_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('legislature', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parliamentary_group_id'], ['parliamentary_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'value', 'legislature', name='uq_group_source_identifiers_source_value_legislature')
    )
    with op.batch_alter_table('parliamentary_group_source_identifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parliamentary_group_source_identifiers_parliamentary_group_id'), ['parliamentary_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parliamentary_group_source_identifiers_source_id'), ['source_id'], unique=False)

    op.create_table('political_party_source_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('political_party_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['political_party_id'], ['political_parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'value', name='uq_party_source_identifiers_source_value')
    )
    with op.batch_alter_table('political_party_source_identifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_political_party_source_identifiers_political_party_id'), ['political_party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_political_party_source_identifiers_source_id'), ['source_id'], unique=False)

    op.create_table('politician_source_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'value', name='uq_politician_source_identifiers_source_value')
    )
    with op.batch_alter_table('politician_source_identifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_politician_source_identifiers_politician_id'), ['politician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_politician_source_identifiers_source_id'), ['source_id'], unique=False)

    op.create_table('politician_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('profile_schema_version', sa.Integer(), nullable=False),
    sa.Column('profile_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('profile_schema_version > 0', name='ck_profile_schema_version_positive'),
    sa.CheckConstraint('version_number > 0', name='ck_version_number_positive'),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('politician_id', 'version_number', name='uq_politician_versions_politician_version')
    )
    with op.batch_alter_table('politician_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_politician_versions_politician_id'), ['politician_id'], unique=False)

    with op.batch_alter_table('politicians', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_politicians_current_version_id',
            'politician_versions',
            ['current_version_id'],
            ['id'],
            ondelete='RESTRICT',
        )

    op.create_table('proposal_actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.Enum('politician', 'political_party', 'institution', name='proposalactortype', native_enum=False, length=32), nullable=False),
    sa.Column('role', sa.Enum('proposer', 'sponsor', 'co_sponsor', 'government', 'commitment_owner', name='proposalactorrole', native_enum=False, length=32), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=True),
    sa.Column('political_party_id', sa.Integer(), nullable=True),
    sa.Column('institution_name', sa.String(length=500), nullable=True),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('source_actor_identifier', sa.String(length=1000), nullable=True),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['political_party_id'], ['political_parties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'identity_key', name='uq_proposal_actor_key')
    )
    with op.batch_alter_table('proposal_actors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_actors_political_party_id'), ['political_party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_actors_politician_id'), ['politician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_actors_proposal_id'), ['proposal_id'], unique=False)

    op.create_table('proposal_source_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('official_identifier', sa.String(length=1000), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'official_identifier', name='uq_proposal_source_identity')
    )
    with op.batch_alter_table('proposal_source_identifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_source_identifiers_proposal_id'), ['proposal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_source_identifiers_source_id'), ['source_id'], unique=False)

    op.create_table('raw_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('raw_sha256', sa.String(length=64), nullable=False),
    sa.Column('normalized_sha256', sa.String(length=64), nullable=True),
    sa.Column('structured_records', sa.JSON(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('process_status', sa.Enum('collected', 'parsed', 'failed', name='rawdocumentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('change_detected', sa.Boolean(), nullable=True),
    sa.Column('collector_version', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_documents_normalized_sha256'), ['normalized_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_documents_process_status'), ['process_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_documents_raw_sha256'), ['raw_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_documents_retrieved_at'), ['retrieved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_documents_source_id'), ['source_id'], unique=False)

    op.create_table('ai_extraction_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='aiextractionrunstatus', native_enum=False, length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('completed_idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('input_chunk_count', sa.Integer(), nullable=False),
    sa.Column('output_candidate_count', sa.Integer(), nullable=False),
    sa.Column('rejected_candidate_count', sa.Integer(), nullable=False),
    sa.Column('abstained_candidate_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_candidate_count', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('completed_idempotency_key', name='uq_ai_extraction_completed_key')
    )
    with op.batch_alter_table('ai_extraction_runs', schema=None) as batch_op:
        batch_op.create_index('ix_ai_extraction_run_document_created', ['raw_document_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_extraction_runs_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_extraction_runs_raw_document_id'), ['raw_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_extraction_runs_status'), ['status'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('chunk_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_document_id', 'chunk_index', name='uq_document_chunk_index')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_document_chunks_document_hash', ['raw_document_id', 'chunk_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_raw_document_id'), ['raw_document_id'], unique=False)

    op.create_table('identity_resolution_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_identifier', sa.String(length=1000), nullable=False),
    sa.Column('candidate_display_name', sa.String(length=500), nullable=False),
    sa.Column('candidate_snapshot', sa.JSON(), nullable=False),
    sa.Column('matching_result_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'resolved_existing', 'resolved_new', 'ignored', name='identityresolutionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('resolved_politician_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_identity', sa.String(length=200), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'pending' AND resolved_at IS NULL AND resolved_politician_id IS NULL AND reviewer_identity IS NULL) OR (status IN ('resolved_existing', 'resolved_new') AND resolved_at IS NOT NULL AND resolved_politician_id IS NOT NULL AND reviewer_identity IS NOT NULL) OR (status = 'ignored' AND resolved_at IS NOT NULL AND resolved_politician_id IS NULL AND reviewer_identity IS NOT NULL)", name='ck_identity_resolution_cases_terminal_fields'),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_politician_id'], ['politicians.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_identifier', name='uq_identity_resolution_cases_source_identifier')
    )
    with op.batch_alter_table('identity_resolution_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_resolution_cases_raw_document_id'), ['raw_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_resolution_cases_resolved_politician_id'), ['resolved_politician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_resolution_cases_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_resolution_cases_status'), ['status'], unique=False)
        batch_op.create_index('ix_identity_resolution_cases_status_created', ['status', 'created_at'], unique=False)

    op.create_table('parliamentary_group_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('parliamentary_group_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.Column('source_identifier', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parliamentary_group_id'], ['parliamentary_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'identity_key', name='uq_group_memberships_source_identity_key')
    )
    with op.batch_alter_table('parliamentary_group_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_group_memberships_politician_dates', ['politician_id', 'start_date', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_parliamentary_group_memberships_parliamentary_group_id'), ['parliamentary_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parliamentary_group_memberships_politician_id'), ['politician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parliamentary_group_memberships_raw_document_id'), ['raw_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parliamentary_group_memberships_source_id'), ['source_id'], unique=False)

    op.create_table('political_party_affiliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('political_party_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.Column('source_identifier', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_field', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('affiliation_type', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['political_party_id'], ['political_parties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'identity_key', name='uq_party_affiliations_source_identity_key')
    )
    with op.batch_alter_table('political_party_affiliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_political_party_affiliations_political_party_id'), ['political_party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_political_party_affiliations_politician_id'), ['politician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_political_party_affiliations_raw_document_id'), ['raw_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_political_party_affiliations_source_id'), ['source_id'], unique=False)

    op.create_table('politician_version_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_version_id', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_field', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['politician_version_id'], ['politician_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('politician_version_id', 'field_path', 'source_name', 'source_url', 'source_field', name='uq_version_citations_public_projection')
    )
    with op.batch_alter_table('politician_version_citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_politician_version_citations_politician_version_id'), ['politician_version_id'], unique=False)
        batch_op.create_index('ix_version_citations_version_field', ['politician_version_id', 'field_path'], unique=False)

    op.create_table('profile_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('baseline_version_id', sa.Integer(), nullable=True),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('initial', 'update', name='profiledraftkind', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_review', 'approved', 'rejected', 'superseded', 'failed', name='profiledraftstatus', native_enum=False, length=32), nullable=False),
    sa.Column('profile_schema_version', sa.Integer(), nullable=False),
    sa.Column('proposed_profile_data', sa.JSON(), nullable=False),
    sa.Column('diff_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_version_id'], ['politician_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['profile_drafts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_drafts_baseline_version_id'), ['baseline_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_drafts_politician_id'), ['politician_id'], unique=False)
        batch_op.create_index('ix_profile_drafts_politician_status', ['politician_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_drafts_raw_document_id'), ['raw_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_drafts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_drafts_supersedes_id'), ['supersedes_id'], unique=False)

    op.create_table('proposal_status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('normalized_status', sa.Enum('announced', 'introduced', 'assigned', 'under_review', 'approved', 'rejected', 'withdrawn', 'enacted', 'completed', 'superseded', 'lapsed', 'returned', name='proposalstatus', native_enum=False, length=64), nullable=False),
    sa.Column('source_status_label', sa.String(length=500), nullable=False),
    sa.Column('effective_at', sa.Date(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_field', sa.String(length=500), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'identity_key', name='uq_proposal_status_event_key')
    )
    with op.batch_alter_table('proposal_status_events', schema=None) as batch_op:
        batch_op.create_index('ix_proposal_status_events_order', ['proposal_id', 'effective_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_status_events_proposal_id'), ['proposal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_status_events_raw_document_id'), ['raw_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_status_events_source_id'), ['source_id'], unique=False)

    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('istat_code', sa.String(length=2), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='territorystatus', native_enum=False, length=16), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('active_until', sa.Date(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('active_until IS NULL OR active_from IS NULL OR active_until >= active_from', name='ck_regions_active_dates'),
    sa.CheckConstraint('length(istat_code) = 2', name='ck_regions_istat_code'),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regions_active_until'), ['active_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_regions_canonical_name'), ['canonical_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_regions_istat_code'), ['istat_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_regions_raw_document_id'), ['raw_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regions_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regions_status'), ['status'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.String(length=500), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_record_identifier', sa.Text(), nullable=False),
    sa.Column('source_field_name', sa.String(length=500), nullable=False),
    sa.Column('source_value', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.Enum('deterministic', name='evidenceextractionmethod', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['profile_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_draft_field_path', ['draft_id', 'field_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_draft_id'), ['draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_raw_document_id'), ['raw_document_id'], unique=False)

    op.create_table('municipalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('istat_code', sa.String(length=6), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('province_abbreviation', sa.String(length=2), nullable=False),
    sa.Column('province_name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='territorystatus', native_enum=False, length=16), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('active_until', sa.Date(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('active_until IS NULL OR active_from IS NULL OR active_until >= active_from', name='ck_municipalities_active_dates'),
    sa.CheckConstraint('length(istat_code) = 6', name='ck_municipalities_istat_code'),
    sa.CheckConstraint('length(province_abbreviation) = 2', name='ck_municipalities_province_abbreviation'),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('municipalities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_municipalities_active_until'), ['active_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_municipalities_canonical_name'), ['canonical_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_municipalities_istat_code'), ['istat_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_municipalities_province_abbreviation'), ['province_abbreviation'], unique=False)
        batch_op.create_index(batch_op.f('ix_municipalities_raw_document_id'), ['raw_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_municipalities_region_id'), ['region_id'], unique=False)
        batch_op.create_index('ix_municipalities_region_province_name', ['region_id', 'province_abbreviation', 'canonical_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_municipalities_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_municipalities_status'), ['status'], unique=False)

    op.create_table('proposal_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('baseline_status_event_id', sa.Integer(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('initial', 'status_update', 'metadata_update', name='proposaldraftkind', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_review', 'approved', 'rejected', 'superseded', name='proposaldraftstatus', native_enum=False, length=32), nullable=False),
    sa.Column('observation_hash', sa.String(length=64), nullable=False),
    sa.Column('proposed_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_status_event_id'], ['proposal_status_events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['proposal_drafts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'observation_hash', name='uq_proposal_draft_observation')
    )
    with op.batch_alter_table('proposal_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_drafts_proposal_id'), ['proposal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_drafts_raw_document_id'), ['raw_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_drafts_status'), ['status'], unique=False)
        batch_op.create_index('ix_proposal_drafts_status_created', ['status', 'created_at'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(length=200), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'rejected', name='reviewdecision', native_enum=False, length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['profile_drafts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', name='uq_reviews_draft_id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_draft_id'), ['draft_id'], unique=False)

    op.create_table('ai_extraction_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('candidate_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'rejected', 'abstained', 'duplicate', name='aiextractioncandidatestatus', native_enum=False, length=32), nullable=False),
    sa.Column('deduplication_key', sa.String(length=64), nullable=True),
    sa.Column('model_output', sa.JSON(), nullable=False),
    sa.Column('observation_data', sa.JSON(), nullable=True),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.Column('proposal_draft_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_draft_id'], ['proposal_drafts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['ai_extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'candidate_index', name='uq_ai_candidate_index')
    )
    with op.batch_alter_table('ai_extraction_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_ai_candidate_run_status', ['run_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_extraction_candidates_proposal_draft_id'), ['proposal_draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_extraction_candidates_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_extraction_candidates_status'), ['status'], unique=False)

    op.create_table('proposal_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_field', sa.String(length=500), nullable=False),
    sa.Column('source_value', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['proposal_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposal_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_evidence_draft_id'), ['draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_evidence_raw_document_id'), ['raw_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_evidence_source_id'), ['source_id'], unique=False)

    op.create_table('proposal_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(length=200), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'rejected', name='proposalreviewdecision', native_enum=False, length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['proposal_drafts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', name='uq_proposal_review_draft')
    )
    with op.batch_alter_table('proposal_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_reviews_draft_id'), ['draft_id'], unique=False)

    op.create_table('territorial_office_mandates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('office', sa.Enum('mayor', 'regional_president', name='territorialoffice', native_enum=False, length=32), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.Column('source_identifier', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(office = 'mayor' AND municipality_id IS NOT NULL AND region_id IS NULL) OR (office = 'regional_president' AND region_id IS NOT NULL AND municipality_id IS NULL)", name='ck_territorial_mandates_office_target'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_territorial_mandates_dates'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'identity_key', name='uq_territorial_mandates_source_identity_key')
    )
    with op.batch_alter_table('territorial_office_mandates', schema=None) as batch_op:
        batch_op.create_index('ix_territorial_mandates_municipality_dates', ['municipality_id', 'start_date', 'end_date'], unique=False)
        batch_op.create_index('ix_territorial_mandates_region_dates', ['region_id', 'start_date', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_office_mandates_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_office_mandates_municipality_id'), ['municipality_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_office_mandates_office'), ['office'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_office_mandates_politician_id'), ['politician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_office_mandates_raw_document_id'), ['raw_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_office_mandates_region_id'), ['region_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_office_mandates_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_office_mandates_start_date'), ['start_date'], unique=False)

    op.create_table('ai_extraction_candidate_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('document_chunk_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('supporting_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['ai_extraction_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_extraction_candidate_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_extraction_candidate_evidence_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_extraction_candidate_evidence_document_chunk_id'), ['document_chunk_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_extraction_candidate_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_extraction_candidate_evidence_document_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_ai_extraction_candidate_evidence_candidate_id'))

    op.drop_table('ai_extraction_candidate_evidence')
    with op.batch_alter_table('territorial_office_mandates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_territorial_office_mandates_start_date'))
        batch_op.drop_index(batch_op.f('ix_territorial_office_mandates_source_id'))
        batch_op.drop_index(batch_op.f('ix_territorial_office_mandates_region_id'))
        batch_op.drop_index(batch_op.f('ix_territorial_office_mandates_raw_document_id'))
        batch_op.drop_index(batch_op.f('ix_territorial_office_mandates_politician_id'))
        batch_op.drop_index(batch_op.f('ix_territorial_office_mandates_office'))
        batch_op.drop_index(batch_op.f('ix_territorial_office_mandates_municipality_id'))
        batch_op.drop_index(batch_op.f('ix_territorial_office_mandates_end_date'))
        batch_op.drop_index('ix_territorial_mandates_region_dates')
        batch_op.drop_index('ix_territorial_mandates_municipality_dates')

    op.drop_table('territorial_office_mandates')
    with op.batch_alter_table('proposal_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_reviews_draft_id'))

    op.drop_table('proposal_reviews')
    with op.batch_alter_table('proposal_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_evidence_source_id'))
        batch_op.drop_index(batch_op.f('ix_proposal_evidence_raw_document_id'))
        batch_op.drop_index(batch_op.f('ix_proposal_evidence_draft_id'))

    op.drop_table('proposal_evidence')
    with op.batch_alter_table('ai_extraction_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_extraction_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_ai_extraction_candidates_run_id'))
        batch_op.drop_index(batch_op.f('ix_ai_extraction_candidates_proposal_draft_id'))
        batch_op.drop_index('ix_ai_candidate_run_status')

    op.drop_table('ai_extraction_candidates')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_draft_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('proposal_drafts', schema=None) as batch_op:
        batch_op.drop_index('ix_proposal_drafts_status_created')
        batch_op.drop_index(batch_op.f('ix_proposal_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_proposal_drafts_raw_document_id'))
        batch_op.drop_index(batch_op.f('ix_proposal_drafts_proposal_id'))

    op.drop_table('proposal_drafts')
    with op.batch_alter_table('municipalities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_municipalities_status'))
        batch_op.drop_index(batch_op.f('ix_municipalities_source_id'))
        batch_op.drop_index('ix_municipalities_region_province_name')
        batch_op.drop_index(batch_op.f('ix_municipalities_region_id'))
        batch_op.drop_index(batch_op.f('ix_municipalities_raw_document_id'))
        batch_op.drop_index(batch_op.f('ix_municipalities_province_abbreviation'))
        batch_op.drop_index(batch_op.f('ix_municipalities_istat_code'))
        batch_op.drop_index(batch_op.f('ix_municipalities_canonical_name'))
        batch_op.drop_index(batch_op.f('ix_municipalities_active_until'))

    op.drop_table('municipalities')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_raw_document_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_draft_id'))
        batch_op.drop_index('ix_evidence_draft_field_path')

    op.drop_table('evidence')
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regions_status'))
        batch_op.drop_index(batch_op.f('ix_regions_source_id'))
        batch_op.drop_index(batch_op.f('ix_regions_raw_document_id'))
        batch_op.drop_index(batch_op.f('ix_regions_istat_code'))
        batch_op.drop_index(batch_op.f('ix_regions_canonical_name'))
        batch_op.drop_index(batch_op.f('ix_regions_active_until'))

    op.drop_table('regions')
    with op.batch_alter_table('proposal_status_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_status_events_source_id'))
        batch_op.drop_index(batch_op.f('ix_proposal_status_events_raw_document_id'))
        batch_op.drop_index(batch_op.f('ix_proposal_status_events_proposal_id'))
        batch_op.drop_index('ix_proposal_status_events_order')

    op.drop_table('proposal_status_events')
    with op.batch_alter_table('profile_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_drafts_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_profile_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_profile_drafts_raw_document_id'))
        batch_op.drop_index('ix_profile_drafts_politician_status')
        batch_op.drop_index(batch_op.f('ix_profile_drafts_politician_id'))
        batch_op.drop_index(batch_op.f('ix_profile_drafts_baseline_version_id'))

    op.drop_table('profile_drafts')
    with op.batch_alter_table('politician_version_citations', schema=None) as batch_op:
        batch_op.drop_index('ix_version_citations_version_field')
        batch_op.drop_index(batch_op.f('ix_politician_version_citations_politician_version_id'))

    op.drop_table('politician_version_citations')
    with op.batch_alter_table('political_party_affiliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_political_party_affiliations_source_id'))
        batch_op.drop_index(batch_op.f('ix_political_party_affiliations_raw_document_id'))
        batch_op.drop_index(batch_op.f('ix_political_party_affiliations_politician_id'))
        batch_op.drop_index(batch_op.f('ix_political_party_affiliations_political_party_id'))

    op.drop_table('political_party_affiliations')
    with op.batch_alter_table('parliamentary_group_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parliamentary_group_memberships_source_id'))
        batch_op.drop_index(batch_op.f('ix_parliamentary_group_memberships_raw_document_id'))
        batch_op.drop_index(batch_op.f('ix_parliamentary_group_memberships_politician_id'))
        batch_op.drop_index(batch_op.f('ix_parliamentary_group_memberships_parliamentary_group_id'))
        batch_op.drop_index('ix_group_memberships_politician_dates')

    op.drop_table('parliamentary_group_memberships')
    with op.batch_alter_table('identity_resolution_cases', schema=None) as batch_op:
        batch_op.drop_index('ix_identity_resolution_cases_status_created')
        batch_op.drop_index(batch_op.f('ix_identity_resolution_cases_status'))
        batch_op.drop_index(batch_op.f('ix_identity_resolution_cases_source_id'))
        batch_op.drop_index(batch_op.f('ix_identity_resolution_cases_resolved_politician_id'))
        batch_op.drop_index(batch_op.f('ix_identity_resolution_cases_raw_document_id'))

    op.drop_table('identity_resolution_cases')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_raw_document_id'))
        batch_op.drop_index('ix_document_chunks_document_hash')

    op.drop_table('document_chunks')
    with op.batch_alter_table('ai_extraction_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_extraction_runs_status'))
        batch_op.drop_index(batch_op.f('ix_ai_extraction_runs_raw_document_id'))
        batch_op.drop_index(batch_op.f('ix_ai_extraction_runs_idempotency_key'))
        batch_op.drop_index('ix_ai_extraction_run_document_created')

    op.drop_table('ai_extraction_runs')
    with op.batch_alter_table('raw_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_documents_source_id'))
        batch_op.drop_index(batch_op.f('ix_raw_documents_retrieved_at'))
        batch_op.drop_index(batch_op.f('ix_raw_documents_raw_sha256'))
        batch_op.drop_index(batch_op.f('ix_raw_documents_process_status'))
        batch_op.drop_index(batch_op.f('ix_raw_documents_normalized_sha256'))

    op.drop_table('raw_documents')
    with op.batch_alter_table('proposal_source_identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_source_identifiers_source_id'))
        batch_op.drop_index(batch_op.f('ix_proposal_source_identifiers_proposal_id'))

    op.drop_table('proposal_source_identifiers')
    with op.batch_alter_table('proposal_actors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_actors_proposal_id'))
        batch_op.drop_index(batch_op.f('ix_proposal_actors_politician_id'))
        batch_op.drop_index(batch_op.f('ix_proposal_actors_political_party_id'))

    op.drop_table('proposal_actors')
    with op.batch_alter_table('politicians', schema=None) as batch_op:
        batch_op.drop_constraint('fk_politicians_current_version_id', type_='foreignkey')
    with op.batch_alter_table('politician_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_politician_versions_politician_id'))

    op.drop_table('politician_versions')
    with op.batch_alter_table('politician_source_identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_politician_source_identifiers_source_id'))
        batch_op.drop_index(batch_op.f('ix_politician_source_identifiers_politician_id'))

    op.drop_table('politician_source_identifiers')
    with op.batch_alter_table('political_party_source_identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_political_party_source_identifiers_source_id'))
        batch_op.drop_index(batch_op.f('ix_political_party_source_identifiers_political_party_id'))

    op.drop_table('political_party_source_identifiers')
    with op.batch_alter_table('parliamentary_group_source_identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parliamentary_group_source_identifiers_source_id'))
        batch_op.drop_index(batch_op.f('ix_parliamentary_group_source_identifiers_parliamentary_group_id'))

    op.drop_table('parliamentary_group_source_identifiers')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_key'))

    op.drop_table('sources')
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposals_published_at'))
        batch_op.drop_index(batch_op.f('ix_proposals_proposal_type'))
        batch_op.drop_index(batch_op.f('ix_proposals_introduced_at'))
        batch_op.drop_index(batch_op.f('ix_proposals_current_status'))

    op.drop_table('proposals')
    with op.batch_alter_table('politicians', schema=None) as batch_op:
        batch_op.drop_index('ix_politicians_normalized_name_birth_date')
        batch_op.drop_index(batch_op.f('ix_politicians_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_politicians_birth_date'))

    op.drop_table('politicians')
    op.drop_table('political_parties')
    with op.batch_alter_table('parliamentary_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parliamentary_groups_legislature'))
        batch_op.drop_index(batch_op.f('ix_parliamentary_groups_institution'))

    op.drop_table('parliamentary_groups')
    with op.batch_alter_table('ingestion_job_runs', schema=None) as batch_op:
        batch_op.drop_index('uq_ingestion_job_runs_running_name', sqlite_where=sa.text("status = 'running'"), postgresql_where=sa.text("status = 'running'"))
        batch_op.drop_index('ix_ingestion_job_runs_status_started')
        batch_op.drop_index(batch_op.f('ix_ingestion_job_runs_status'))
        batch_op.drop_index(batch_op.f('ix_ingestion_job_runs_source_key'))
        batch_op.drop_index('ix_ingestion_job_runs_name_started')
        batch_op.drop_index(batch_op.f('ix_ingestion_job_runs_job_name'))

    op.drop_table('ingestion_job_runs')
    with op.batch_alter_table('ai_extraction_evaluation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_extraction_evaluation_runs_status'))
        batch_op.drop_index(batch_op.f('ix_ai_extraction_evaluation_runs_dataset_version'))

    op.drop_table('ai_extraction_evaluation_runs')
    # ### end Alembic commands ###
